<?php
	/*   
	WARNING!!
	This is a dynamically generated style sheet that is controlled by the Wordpress admin
	"Theme Options" area. We suggest that you do not edit this file. If you would like to
	use your own custom styles you can override the dynamic styling in the Wordpress admin
	and use the standard style sheet provided with your theme located in your theme directory
	called style.css.
	*/

	define('ABSPATH', dirname(dirname(dirname(dirname(dirname(__FILE__))))).'/');
	include_once(ABSPATH.'wp-config.php');
	include_once(ABSPATH.'wp-load.php');
	include_once(ABSPATH.'wp-includes/wp-db.php');
	
	@header( 'Content-type: text/css' ); 
	
	// Gets the NextGen options from the DB
	$ngg_options = get_option('ngg_options');
	
	global $wpdb;
	
	global $shortname;
	$settings = get_option($shortname.'_options');
	// Options are called like this $settings['option_id'];
	
	$style = $wpdb->get_results("SELECT * FROM ".$wpdb->prefix."photocrati_styles WHERE option_set = 1");
	foreach ($style as $style) {
		$content_width = $style->content_width;
		$sidebar_width = $style->sidebar_width;
		$logo_menu_position = $style->logo_menu_position;
		$header_bg_color = $style->header_bg_color;
		$header_bg_image = $style->header_bg_image;
		$header_bg_repeat = $style->header_bg_repeat;
		$bg_color = $style->bg_color;
		$bg_image = $style->bg_image;
		$bg_repeat = $style->bg_repeat;
		$container_color = $style->container_color;
		$container_border = $style->container_border;
		$container_border_color = $style->container_border_color;
		$font_color = $style->font_color;
		$font_size = $style->font_size;
		$font_style = $style->font_style;
		$h1_color = $style->h1_color;
		$h1_size = $style->h1_size;
		$h2_color = $style->h2_color;
		$h2_size = $style->h2_size;
		$h3_color = $style->h3_color;
		$h3_size = $style->h3_size;
		$h4_color = $style->h4_color;
		$h4_size = $style->h4_size;
		$h5_color = $style->h5_color;
		$h5_size = $style->h5_size;
		$link_color = $style->link_color;
		$link_hover_color = $style->link_hover_color;
		$link_hover_style = $style->link_hover_style;
		$sidebar_bg_color = $style->sidebar_bg_color;
		$sidebar_font_color = $style->sidebar_font_color;
		$sidebar_font_size = $style->sidebar_font_size;
		$sidebar_font_style = $style->sidebar_font_style;
		$sidebar_title_color = $style->sidebar_title_color;
		$sidebar_title_size = $style->sidebar_title_size;
		$sidebar_title_style = $style->sidebar_title_style;
		$sidebar_link_color = $style->sidebar_link_color;
		$sidebar_link_hover_color = $style->sidebar_link_hover_color;
		$sidebar_link_hover_style = $style->sidebar_link_hover_style;
		$menu_style = $style->menu_style;
		$menu_color = $style->menu_color;
		$menu_hover_color = $style->menu_hover_color;
		$menu_font_size = $style->menu_font_size;
		$menu_font_style = $style->menu_font_style;
		$menu_font_color = $style->menu_font_color;
		$menu_font_hover_color = $style->menu_font_hover_color;
		$submenu_color = $style->submenu_color;
		$submenu_hover_color = $style->submenu_hover_color;
		$submenu_font_size = $style->submenu_font_size;
		$submenu_font_style = $style->submenu_font_style;
		$submenu_font_color = $style->submenu_font_color;
		$submenu_font_hover_color = $style->submenu_font_hover_color;
		$nextgen_border = $style->nextgen_border;
		$nextgen_border_color = $style->nextgen_border_color;
		$custom_css = $style->custom_css;
		$header_height = $style->header_height;
		$header_logo_margin_above = $style->header_logo_margin_above;
		$header_logo_margin_below = $style->header_logo_margin_below;
		$title_color = $style->title_color;
		$title_size = $style->title_size;
		$title_style = $style->title_style;
		$description_color = $style->description_color;
		$description_size = $style->description_size;
		$description_style = $style->description_style;
		$bg_top_offset = $style->bg_top_offset;
		$container_padding = $style->container_padding;
		$footer_font = $style->footer_font;
		$footer_font_color = $style->footer_font_color;
	}
?>

/* Reset default browser styles */
@import url('resets/reset.css');

/* Rebuild default browser styles */
@import url('resets/rebuild.css');

/* Basic WordPress Styles */
@import url('resets/wp.css');

/* General Styles
-------------------------------------------------------------- */

/* The following section sets the basic body, H1-H5 and link styles */

body {
	background		: 	<?php if($bg_image <> '') { ?>url(../images/uploads/<?php echo $bg_image; ?>) <?php echo $bg_repeat; ?><?php } ?> 0 <?php echo $bg_top_offset; ?>px #<?php echo $bg_color; ?>;
    padding-top 	: 	0;
	margin-top 		: 	0;
}

h1 { /* The H1 tag is used for page titles */
	font-size 		: 	<?php echo $h1_size; ?>px;
	font-weight		:	bold;
    color			: 	#<?php echo $h1_color; ?>;
    padding-bottom	:	15px;
    margin-bottom	:	10px;
    border-bottom	:	1px solid #E1E1E1;
}

h1 a:link, .h1 a:visited {
	color			: 	#<?php echo $h1_color; ?>;
}

h2 { /* The H2 tag is used for post titles */
	font-size 		: 	<?php echo $h2_size; ?>px;
	font-weight		:	bold;
    color			: 	#<?php echo $h2_color; ?>;
}

h2 a:link, .h2 a:visited {
	color			: 	#<?php echo $h2_color; ?>;
}

h3 {
	font-size 		: 	<?php echo $h3_size; ?>px;
	font-weight		:	bold;
    color			: 	#<?php echo $h3_color; ?>;
}

h3 a:link, .h1 a:visited {
	color			: 	#<?php echo $h3_color; ?>;
}

h4 {
	font-size 		: 	<?php echo $h4_size; ?>px;
	font-weight		:	bold;
    color			: 	#<?php echo $h4_color; ?>;
}

h4 a:link, .h4 a:visited {
	color			: 	#<?php echo $h4_color; ?>;
}

h5 {
	font-size 		: 	<?php echo $h5_size; ?>px;
	font-weight		:	bold;
    color			: 	#<?php echo $h5_color; ?>;
}

h5 a:link, .h5 a:visited {
	color			: 	#<?php echo $h5_color; ?>;
}

a:link,a:visited { /* This styles the majority of the on page links. The sidebar links can be styled seperately */
	color 			: 	#<?php echo $link_color; ?>;
	text-decoration : 	none;
}

a:hover,a:active {
	color 			: 	#<?php echo $link_hover_color; ?>;
	text-decoration : 	<?php echo $link_hover_style; ?>;
}


/* NextGen Gallery Styles
-------------------------------------------------------------- */

div.slideshow { /* Main page slideshow wrapper */
	border 			: 	<?php echo $nextgen_border; ?>px solid #<?php echo $nextgen_border_color; ?>;
    width			:	<?php echo $ngg_options['irWidth']; ?>px;
    margin			:	0 auto;
}

/* The following align single NextGen images */

img.ngg-left {
	float			:	left;
    margin-right	:	10px;
}

img.ngg-right {
	float			:	right;
    margin-left		:	10px;
}

img.ngg-center {
	display			:	block;
    margin			:	5px auto;
}

div.ngg-clear { /* This makes sure text does not wrap around galleries */
	width			:	100%;
	clear			:	both;
}


/* General Page Styles
-------------------------------------------------------------- */

#wrapper { /* This sets the width of the entire site */
	position 		: 	relative;
	width 			: 	960px;
	margin 			: 	0 auto;
}

#container { /* This sets the width of the main content area */
	float			: 	left;
	margin			: 	0;
	width			: 	<?php echo 960 - ((int)$container_padding * 2) - ((int)$container_border * 2); ?>px;
    padding			: 	<?php echo $container_padding; ?>px;
	background		: 	<?php if($container_color <> 'transparent') { echo '#'; } ?><?php echo $container_color; ?>;
    border			:	<?php echo $container_border; ?>px solid #<?php echo $container_border_color; ?>;
}


/* Menu Styles
-------------------------------------------------------------- */

#menu_wrapper { /* This is the main menu container */
	<?php if($logo_menu_position == 'left-right') { ?>
	width 			: 	600px;
    margin			: 	30px 10px 0 0;
	float 			: 	right;
	text-align 		: 	right;
    position		:	relative;
    <?php } else if($logo_menu_position == 'right-left') { ?>
	width 			: 	600px;
    margin			: 	30px 0 0 10px;
    float 			: 	left;
	text-align 		: 	left;
    position		:	relative;
    <?php } else if($logo_menu_position == 'bottom-top') { ?>
    width 			: 	100%;
    margin			: 	0 0 1.5em 0;
	position 		: 	absolute;
	top 			: 	0;
	left 			: 	0;
	text-align 		: 	center;
    <?php } else if($logo_menu_position == 'top-bottom') { ?>
    width 			: 	100%;
    margin			: 	0 0 1.5em 0;
	clear			:	both;
	text-align 		: 	center;
    position		:	relative;
    <?php } ?>
	overflow 		: 	visible;
	padding-top 	: 	22px;
    z-index			:	2;
}

.menu ul, .menu ul * { /* This sets the width of the menu */
	list-style		: 	none;
	margin			: 	0;
	padding			:	0;
}

.menu ul { /* This sets the line height of the menu */
	line-height		:	1.0;
}

.menu a { /* This controls the font size and position of the main menu links */
	position		:	relative;
	display			: 	block;
	float			: 	left;
    font-size 		: 	<?php echo $menu_font_size; ?>px;
}

.menu a:link,.menu a:visited { /* This sets the color and style of the main menu links */
	display 		: 	inline;
	float 			: 	none;
	text-decoration : 	none;
	color 			: 	#<?php echo $menu_font_color; ?>;
    font-family		:	<?php echo str_replace('\"', '"', $menu_font_style); ?>;
	font-weight 	: 	bold;
	text-transform 	: 	uppercase;
	padding 		: 	22px 17px 12px 17px;
	background 		: 	<?php if($menu_style <> 'transparent') { echo '#'.$menu_color; } else { echo $menu_style; } ?>;
}

.menu a:hover,.menu a:active,
.menu .current_page_item a:link,
.menu .current_page_item a:visited  { /* This sets the color and style of the hover and active states of the main menu links */
	color 			: 	#<?php echo $menu_font_hover_color; ?>;
	background 		: 	<?php if($menu_style <> 'transparent') { echo '#'.$menu_hover_color; } else { echo $menu_style; } ?>;
}

.menu .current_page_item ul a:link,
.menu .current_page_item ul a:visited { /* This sets the color and style of the current page item on the main menu links */
	color 			: 	#<?php echo $menu_font_hover_color; ?>;
	background 		: 	#<?php echo $menu_hover_color; ?>;
}

.menu .current_page_item ul li a:hover,
.menu .current_page_item ul li a:active { /* This sets the color and style of the hover and active states of the current page item on the main menu links */
	color 			: 	#<?php echo $menu_font_hover_color; ?>;
	background 		: 	#<?php echo $menu_hover_color; ?>;
}

.menu ul li { /* This sets the position of the main menu items */
	position		:	relative;
	display			: 	inline;
    margin			:	0 0 0 0;
}

.menu ul li { /* This sets the position of the custom main menu items */
	position		:	relative;
	display			: 	inline;
    margin			:	0 -3px 0 0;
}

.menu ul li:hover {
	visibility		:	inherit; /* fixes IE7 'sticky bug' */
}

.menu ul li ul { /* This sets the position of the dropdown menu */
	display			: 	none;
    position		:	absolute;
	top				:	-999em;
    margin			:	0 0 0 0;
	width			:	10em; /* left offset of submenus need to match (see below) */
    border-top		:	2px solid #<?php echo $menu_font_hover_color; ?>;
}

.menu ul li:hover ul,
.menu ul li ul { /* This sets the position and z-index of the dropdown menu */
	left			:	0;
	top				:	2.2em; /* match top ul list item height */
	z-index			:	99;
}

.menu ul li ul li { /* This sets the size and transparency of the dropdown items */
	display 		: 	block;
	width			:	100%;
	filter			:	alpha(opacity=90);
	opacity			: 	0.90;
	-moz-opacity	:	0.90;
    margin			:	0;
}

.menu ul li ul li a:link,
.menu ul li ul li a:visited,
.menu ul li.current_page_item ul li a:link,
.menu ul li.current_page_item ul li a:visited { /* This sets the color and style of the drop down menu links */
	display 		: 	block;
	padding 		: 	5px;
	text-align 		: 	left;
	color 			: 	#<?php echo $submenu_font_color; ?>;
	background 		: 	#<?php echo $submenu_color; ?>;
    font-size 		: 	<?php echo $submenu_font_size; ?>px;
    font-family		:	<?php echo str_replace('\"', '"', $submenu_font_style); ?>;
}

.menu ul li ul li a:hover,
.menu ul li ul li a:active,
.menu ul li.current_page_item ul li a:hover,
.menu ul li.current_page_item ul li a:active,
.menu ul li ul li.current_page_item a:link,
.menu ul li ul li.current_page_item a:visited { /* This sets the color and style of the hover, active & current states of the drop down menu links */
	color 			: 	#<?php echo $submenu_font_hover_color; ?>;
	background 		: 	#<?php echo $submenu_hover_color; ?>;
}

 /* The remaining items below are essential positioning styles for the menus */

.menu ul li:hover li ul,
.menu ul li li ul {
	top				:	-999em;
}

.menu ul li li:hover ul,
.menu ul li li ul {
	left			:	10em; /* match ul width */
	top				:	0;
}

.menu ul li li:hover li ul,
.menu ul li li li ul {
	top				:	-999em;
}

.menu ul li li li:hover ul,
.menu ul li li li ul {
	left			:	10em; /* match ul width */
	top				:	0;
}

.footer_menu ul, .footer_menu ul * { /* This sets the width of the footer menu */
	overflow 		: 	visible;
    z-index			:	2;
    list-style		: 	none;
    margin			:	0 auto;
	padding			:	0;
}

.footer_menu ul li { /* This sets the position of the footer menu items */
	position		:	relative;
	display			: 	inline;
    margin			:	0 7px 0 7px;
    font-weight		:	bold;
}


/* Header Styles
-------------------------------------------------------------- */

#header { /* This sets the color of the header */
	background		:	<?php if($header_bg_image <> '') { ?>url(../images/uploads/<?php echo $header_bg_image; ?>) bottom <?php echo $header_bg_repeat; ?><?php } ?> #<?php echo $header_bg_color; ?>;
    width			:	100%;
    height			:	<?php echo $header_height; ?>px;
    margin-bottom	:	10px;
}

#masthead { /* This sets total width and position of the header */
    width			:	960px;
    margin			:	0 auto;
}

#branding { /* This sets the size and position of the logo area on the header */
    display			:	block;
	<?php if($logo_menu_position == 'left-right') { ?>
	width 			: 	300px;
	float 			: 	left;
    margin			:	0;
    <?php } else if($logo_menu_position == 'right-left') { ?>
	width 			: 	300px;
	float 			: 	right;
    text-align		:	right;
    margin			:	0;
    <?php } else if($logo_menu_position == 'bottom-top') { ?>
	width 			: 	100%;
	text-align 		: 	center;
    margin			:	0 0 24px 0;
    <?php } else if($logo_menu_position == 'top-bottom') { ?>
	width 			: 	100%;
	text-align 		: 	center;
    margin			:	0 0 5px 0;
    <?php } ?>
    padding			:	<?php echo $header_logo_margin_above; ?>px 0 <?php echo $header_logo_margin_below; ?>px 0;
}

#branding a { /* This sets the color and style of the wordpress title */
    text-decoration	:	none;
}

#branding h1 { /* This sets the color of the wordpress title */
	font-size		:	<?php echo $title_size; ?>px;
    font-family		:	<?php echo str_replace('\"', '"', $title_style); ?>;
	color			: 	#<?php echo $title_color; ?>;
    border			:	0;
    margin-bottom	:	5px;
    padding			:	0;
}

#branding .description { /* This sets the font size and color for the description line if you are using the Wordpress title and description */
	font-size		:	<?php echo $description_size; ?>px;
    font-family		:	<?php echo str_replace('\"', '"', $description_style); ?>;
	color			: 	#<?php echo $description_color; ?>;
}


/* Content Styles
-------------------------------------------------------------- */

#content { /* This sets the width of the page content area  */
	position		:	relative;
    margin			: 	0;
	width			:	100%;
    z-index			:	1;
}

#content-sm { /* This sets the width of the blog content area  */
	width			:	<?php echo (int)$content_width - 2; ?>%;
    float			:	left;
    padding-right	:	2%; /* IMPORTANT! Sets a small margin between the blog content and the sidebar  */
}

#content, #content-sm { /* This sets the font size and style on the blog and pages  */
	color 			: 	#<?php echo $font_color; ?>;
    font-size		: 	<?php echo $font_size; ?>px;
    font-family		:	<?php echo str_replace('\"', '"', $font_style); ?>;
}

.post { /* This sets a small margin at the bottom of posts  */
	margin			: 	0 0 3em 0;	
}

.entry-content, .entry-summary { /* This sets a small margin at the top of the post content to make space between the title/meta area  */
	margin			: 	1.5em 0 0 0;
}

blockquote { /* This styles blockquotes in blog posts  */
	border-left		:	2px solid #E1E1E1;
	margin-left		:	25px;
	padding-left	:	15px;
}


/* Post Styles
-------------------------------------------------------------- */

.navigation { /* This sets a small margin below the post navigation on a single post */
	margin			: 	0 0 1.5em 0;
	overflow		: 	auto;	
}

.size-full,
.entry-content img { /* This sets a border around images in posts */
	border 			: 	5px solid #e8e7e7;
}

.entry-meta,
.entry-utility { /* This sets the font size and style on post meta. This is the date, post by and comment links below the post title. */
	color 			: 	#<?php echo $font_color; ?>;
    font-size		: 	<?php echo $font_size; ?>px;
    font-family		:	<?php echo str_replace('\"', '"', $font_style); ?>;
	font-style 		: 	italic;
	clear 			: 	both;
}


/* Post Comment Styles
-------------------------------------------------------------- */

.comments ol { /* This removes the numbers from the comment list */
	list-style		:	none;	
    margin-top		:	10px;
}

.comments li { /* This clears each comment block to a new line and adds a margin */
	width			:	100%;
    clear			:	both;
    min-height		:	100px;
}

.comments .comment-wrapper { /* This sets the style for the comment wrapper */
	display			:	block;
}

.comments .comment-author { /* This sets the style for the comment author icon */
	float			:	left;
    width			:	15%;
    margin-right	:	2%;
}

.comments .content-wrapper { /* This sets the style for the comment meta and content */
	float			:	left;
    width			:	83%;
}

.comments .comment-content { /* This sets a small margin between the meta and comment content */
	margin-top		:	5px;
}

span.unapproved {
	font-style 		: 	italic;
}

img.wp-smiley{  /* This sets no border around smileys */
	border			:	none;
}


/* Sidebar Styles
-------------------------------------------------------------- */

#sidebar { /* This sets the size of the sidebar as well as the font size and style */
	float			:	right;
	width			: 	<?php echo $sidebar_width; ?>%;
    background		:	<?php if($sidebar_bg_color <> 'transparent') { echo '#'; } ?><?php echo $sidebar_bg_color; ?>;
    text-align		:	center;
    color			:	#<?php echo $sidebar_font_color; ?>;
    font-size		:	<?php echo $sidebar_font_size; ?>px;
    font-family		:	<?php echo str_replace('\"', '"', $sidebar_font_style); ?>;
}

#sidebar a { /* This sets the color of the sidebar links */
    color			:	#<?php echo $sidebar_link_color; ?>;
}

#sidebar a:hover,
#sidebar a:active { /* This sets the color and style of the hover and active states of the sidebar links */
    color			:	#<?php echo $sidebar_link_hover_color; ?>;
    text-decoration	:	<?php echo $sidebar_link_hover_style; ?>;
}

#sidebar .social-media { /* This sets the padding of the social media icons in the sidebar */
    text-align		:	left;
    padding			:	10px 10px 5px 10px;
}

#sidebar .social-media img { /* This sets a small margin to the right of each of the social media icons */
    border			:	0;
    margin-right	:	5px;
}

#primary { /* This sets the position and width of the widget area */
	float			: 	right;
	overflow		: 	hidden;
	width 			: 	94%;
    padding			:	3%;
    text-align		:	left;
}

.widget-title,.widgettitle { /* This sets the size and style of the sidebar titles */
	font-size 		: 	<?php echo $sidebar_title_size; ?>px;
	font-weight 	: 	bold;
    font-family		:	<?php echo str_replace('\"', '"', $sidebar_title_style); ?>;
	color 			: 	#<?php echo $sidebar_title_color; ?>;
	text-transform 	: 	uppercase;
	margin-bottom 	: 	10px;
	padding-bottom 	: 	0;
}

.widget-container { /* This sets a small margin below each widget */
	margin			: 	0 0 1.5em 0;
}

#searchform label { /* This hides the search form label */
	display 		: 	none;
}

/* The following style the lists in the widgets */

.widget-area ul {
	list-style		: 	none;
	margin-left		: 	0;
}

.widget-area ul ul {
	list-style		: 	disc;
	margin-left		: 	1.1em;
}

.widget-area ul ul ul {
	margin-left		: 	2.5em;
}

/* Footer Widget Styles
-------------------------------------------------------------- */

.footer-widget-area { /* This is the footer widget wrapper */
	display			:	inline-block;
	width			:	<?php echo 960 - ((int)$container_padding * 2) - ((int)$container_border * 2); ?>px;
    min-height		:	50px;
    background		:	<?php if($sidebar_bg_color <> 'transparent') { echo '#'; } ?><?php echo $sidebar_bg_color; ?>;
    color			:	#<?php echo $sidebar_font_color; ?>;
    font-size		:	<?php echo $sidebar_font_size; ?>px;
    font-family		:	<?php echo str_replace('\"', '"', $sidebar_font_style); ?>;
    margin-top		:	15px;
}

.footer-widget-container { /* This is the footer widget container */
	display			:	inline-block;
    height			:	auto;
    float			:	left;
	padding			:	10px;
}

.footer-widget-container a { /* This sets the color of the footer widget links */
    color			:	#<?php echo $sidebar_link_color; ?>;
}

.footer-widget-container a:hover,
.footer-widget-container a:active { /* This sets the color and style of the hover and active states of the footer widget links */
    color			:	#<?php echo $sidebar_link_hover_color; ?>;
    text-decoration	:	<?php echo $sidebar_link_hover_style; ?>;
}


/* Footer Style
-------------------------------------------------------------- */

#footer { /* This sets the size and font styles of the footer area */
	clear			: 	both;
	width			: 	100%;
	text-align 		: 	right;
	margin-top		:	10px;
	padding-top 	: 	5px;
    border-top		:	1px solid #e8e7e7;
	color 			: 	#<?php echo $footer_font_color; ?>;
    font-size		: 	<?php echo $footer_font; ?>px;
    font-family		:	<?php echo str_replace('\"', '"', $font_style); ?>;
}

#footer #site-info {
	clear			: 	both;
	margin			:	5px 7px 0 7px;
}


/* Custom CSS Code
-------------------------------------------------------------- */

<?php 
echo str_replace("\'", "'", str_replace('\"', '"', $custom_css)); 
?>